### ISSUE TITLE
Consider copper filling/pouring in the ground plane

### ISSUE THREAD

**Issue by jcoffland** [buildbotics/bbctrl-pcb#15]
Isn't it generally a good idea to copper fill the ground plane?  You've done this already for the motor ground but why not also do so for the logic ground plane?  I was able to do this by drawing a few polygons on layer `inner 2` so that they did not overlap the motor ground plane.  I didn't check this in though.  What do you think?

**Comment by sntanala** [comment]
Hi jcoffland, my name is Satya, I am a learner and programmer for cnc controller, can you please let us know how can i open eagle schematics of this project, I tried all versions of eagle but we are getting error while open. can you please suggest me how to open these schematics to learn control flows.
